#!/bin/bash
screen -dmS diff_OLHU_vsepsilon_zipf_AO_0_SP_10 bash -c 'python -m Fake_User_Detection --splits=10 --h_ao=0 --vswhat=epsilon --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_0_SP_8 bash -c 'python -m Fake_User_Detection --splits=8  --h_ao=0 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_0_SP_6 bash -c 'python -m Fake_User_Detection --splits=6 --h_ao=0 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_0_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=0 --vswhat=epsilon --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_0_SP_2 bash -c 'python -m Fake_User_Detection --splits=2 --h_ao=0 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_1_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=1 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_2_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=2 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_5_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=5 --vswhat=epsilon --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_8_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=8 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_10_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=10 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_5_SP_2 bash -c 'python -m Fake_User_Detection --splits=2 --h_ao=5 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_5_SP_6 bash -c 'python -m Fake_User_Detection --splits=6 --h_ao=5 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_5_SP_8 bash -c 'python -m Fake_User_Detection --splits=8 --h_ao=5 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsepsilon_zipf_AO_5_SP_10 bash -c 'python -m Fake_User_Detection --splits=10 --h_ao=5 --vswhat=epsilon_1 --dataset=zipf --protocol=OUE'

screen -dmS diff_OLHU_vsbeta_zipf_AO_0_SP_10 bash -c 'python -m Fake_User_Detection --splits=10 --h_ao=0 --vswhat=beta --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsbeta_zipf_AO_0_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=0 --vswhat=beta --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsbeta_zipf_AO_5_SP_4 bash -c 'python -m Fake_User_Detection --splits=4 --h_ao=5 --vswhat=beta --dataset=zipf --protocol=OUE'
screen -dmS diff_OLHU_vsr_zipf_AO_0_SP_r bash -c 'python -m Fake_User_Detection --splits=10 --h_ao=0 --vswhat=r --dataset=zipf --protocol=OUE'
